# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/hermes

PRODUCT_COPY_FILES += \
    vendor/xiaomi/hermes/proprietary/etc/mtk_clear_motion.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/mtk_clear_motion.cfg \
    vendor/xiaomi/hermes/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/xiaomi/hermes/proprietary/vendor/bin/6620_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/6620_launcher \
    vendor/xiaomi/hermes/proprietary/vendor/bin/autokd:$(TARGET_COPY_OUT_VENDOR)/bin/autokd \
    vendor/xiaomi/hermes/proprietary/vendor/bin/bmi160d:$(TARGET_COPY_OUT_VENDOR)/bin/bmi160d \
    vendor/xiaomi/hermes/proprietary/vendor/bin/ccci_fsd:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_fsd \
    vendor/xiaomi/hermes/proprietary/vendor/bin/ccci_mdinit:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_mdinit \
    vendor/xiaomi/hermes/proprietary/vendor/bin/fuelgauged:$(TARGET_COPY_OUT_VENDOR)/bin/fuelgauged \
    vendor/xiaomi/hermes/proprietary/vendor/bin/gas_srv:$(TARGET_COPY_OUT_VENDOR)/bin/gas_srv \
    vendor/xiaomi/hermes/proprietary/vendor/bin/ged_srv:$(TARGET_COPY_OUT_VENDOR)/bin/ged_srv \
    vendor/xiaomi/hermes/proprietary/vendor/bin/gsm0710muxd:$(TARGET_COPY_OUT_VENDOR)/bin/gsm0710muxd \
    vendor/xiaomi/hermes/proprietary/vendor/bin/guiext-server:$(TARGET_COPY_OUT_VENDOR)/bin/guiext-server \
    vendor/xiaomi/hermes/proprietary/vendor/bin/hw/android.hardware.drm@1.1-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.1-service.widevine \
    vendor/xiaomi/hermes/proprietary/vendor/bin/md_ctrl:$(TARGET_COPY_OUT_VENDOR)/bin/md_ctrl \
    vendor/xiaomi/hermes/proprietary/vendor/bin/mtk_agpsd:$(TARGET_COPY_OUT_VENDOR)/bin/mtk_agpsd \
    vendor/xiaomi/hermes/proprietary/vendor/bin/muxreport:$(TARGET_COPY_OUT_VENDOR)/bin/muxreport \
    vendor/xiaomi/hermes/proprietary/vendor/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    vendor/xiaomi/hermes/proprietary/vendor/bin/thermal_manager:$(TARGET_COPY_OUT_VENDOR)/bin/thermal_manager \
    vendor/xiaomi/hermes/proprietary/vendor/bin/wifi2agps:$(TARGET_COPY_OUT_VENDOR)/bin/wifi2agps \
    vendor/xiaomi/hermes/proprietary/vendor/bin/wmt_loader:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_loader \
    vendor/xiaomi/hermes/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/xiaomi/hermes/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/xiaomi/hermes/proprietary/vendor/etc/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/agps_profiles_conf2.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/A4_15_2.2_AA.fw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/A4_15_2.2_AA.fw \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/A4_15_2.2_AA.raw:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/A4_15_2.2_AA.raw \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/S_ANDRO_SFL.ini:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/S_ANDRO_SFL.ini \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/WIFI_RAM_CODE_MT6630:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/WMT.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/WMT.cfg \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/WMT_SOC.cfg \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/catcher_filter_1_ltg_n.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/catcher_filter_1_ltg_n.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/catcher_filter_1_lwg_n.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/catcher_filter_1_lwg_n.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/dsp_1_ltg_n.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/dsp_1_ltg_n.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/dsp_1_lwg_n.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/dsp_1_lwg_n.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/md32_d.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/md32_d.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/md32_p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/md32_p.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/modem_1_ltg_n.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/modem_1_ltg_n.img \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/modem_1_lwg_n.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/modem_1_lwg_n.img \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v1_coeff.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v1_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v1_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v1_patch.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v1_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v1_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v2_coeff.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v2_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v2_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v2_patch.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v2_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v2_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v3_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v3_coeff.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v3_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v3_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v3_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v3_patch.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v3_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v3_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v4_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v4_coeff.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v4_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v4_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v4_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v4_patch.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v4_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v4_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v5_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v5_coeff.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v5_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v5_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v5_patch.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v5_patch.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630/mt6630_fm_v5_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630/mt6630_fm_v5_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630_ant_m1.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630_ant_m1.cfg \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630_patch_e1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630_patch_e1_hdr.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630_patch_e2_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630_patch_e2_hdr.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630_patch_e3_0_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630_patch_e3_0_hdr.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/firmware/mt6630_patch_e3_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/mt6630_patch_e3_1_hdr.bin \
    vendor/xiaomi/hermes/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/autokd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/autokd.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/bmi160d.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bmi160d.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/ccci_fsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ccci_fsd.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/ccci_mdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ccci_mdinit.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/charger.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/charger.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/fuelgauged.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/hw/init.mt6795.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6795.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/hw/init.mt6795.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6795.usb.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/md_ctrl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/md_ctrl.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/mnld.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mnld.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/mtk_agpsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/pvrsrvctl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pvrsrvctl.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/thermal_manager.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/wifi2agps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi2agps.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/wmt_launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wmt_launcher.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/wmt_loader.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wmt_loader.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/init/wpa_supplicant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wpa_supplicant.rc \
    vendor/xiaomi/hermes/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/media_codecs_mediatek_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_audio.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/media_codecs_mediatek_video.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_video.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/xiaomi/hermes/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/xiaomi/hermes/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/xiaomi/hermes/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/xiaomi/hermes/proprietary/vendor/etc/sensor/softiron_matrix_akm09911.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensor/softiron_matrix_akm09911.txt \
    vendor/xiaomi/hermes/proprietary/vendor/etc/sensor/softiron_matrix_yas537.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensor/softiron_matrix_yas537.txt \
    vendor/xiaomi/hermes/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/xiaomi/hermes/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/xiaomi/hermes/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libEGL_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libGLESv2_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/audio.primary.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/camera.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/consumerir.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/consumerir.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/gatekeeper.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/gps.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/gralloc.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/hwcomposer.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/lights.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/lights.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/memtrack.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/sensors.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/lib3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/lib3a_sample.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a_sample.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libClearMotionFW.so:$(TARGET_COPY_OUT_VENDOR)/lib/libClearMotionFW.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libIMGegl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libIMGegl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libJpgDecPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libJpgDecPipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libJpgEncPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libJpgEncPipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkH264SecVdecTLCLib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkH264SecVdecTLCLib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkH264SecVencTLCLib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkH264SecVencTLCLib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxAdpcmDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxAdpcmDec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxAdpcmEnc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxAdpcmEnc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxAlacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxAlacDec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxApeDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxApeDec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxCore.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxG711Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxG711Dec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxGsmDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxGsmDec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxMp3Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxMp3Dec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxRawDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxRawDec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxVdecEx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVdecEx.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxVenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVenc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVorbisEnc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libPVROCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPVROCL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libSwJpgCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSwJpgCodec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaed.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaed.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libandroid_net.so:$(TARGET_COPY_OUT_VENDOR)/lib/libandroid_net.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosetting.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbessound_hd_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc32.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_mtk_pure.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libbwc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbwc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.camadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camadapter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.camnode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camnode.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.camshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camshot.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.device1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.device1.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.exif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.exif.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.v3.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.halsensor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.halsensor.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.iopipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.iopipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.metadata.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadata.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.metadataprovider.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadataprovider.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.paramsmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.paramsmgr.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.sdkclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.sdkclient.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.utils.cpuctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.utils.cpuctrl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam1_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam1_utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam3_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam_hwutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_hwutils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam_mmp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_mmp.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcam_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_platform.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcamalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamalgo.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcamdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamdrv.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libccci_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libccci_util.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_nvram.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcvsd_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libdngop.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdngop.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libfeatureio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureio.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libfgauge.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfgauge.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfile_op.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libfmcust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfmcust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libgas.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgas.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libglslcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglslcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libgpu_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgpu_aux.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libhwm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwm.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libimageio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libimageio_plat_drv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio_plat_drv.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/liblic_divx.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblic_divx.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/liblic_s263.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblic_s263.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libm4u.so:$(TARGET_COPY_OUT_VENDOR)/lib/libm4u.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmatv_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmatv_cust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmdfx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdfx.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmemtrack_GL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmemtrack_GL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmhalImageCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmhalImageCodec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmjc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmjc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmmprofile.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmprofile.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmmsdkservice.feature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmsdkservice.feature.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmmsdkservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmsdkservice.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmnl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmnl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmp4enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmp4enc_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmrdump.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmrdump.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsbc_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtcloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtcloader.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtk_drvb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_drvb.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtk_mmutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_mmutils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtkcamera_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcamera_client.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtkjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkjpeg.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtklimiter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkshifter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libn3d3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libn3d3a.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_daemon_callback.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_platform.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libnvram_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_sec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvramagentclient.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/liboclcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboclcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libperfservicenative.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperfservicenative.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libpq_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpq_cust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libpq_prot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpq_prot.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libpqservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpqservice.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpvrANDROID_WSEGL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/librrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/librrc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libspeech_enh_lib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libsrv_um.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsrv_um.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libufwriter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libufwriter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libusc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libusc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvc1dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvc1dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvcodec_cap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_cap.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvcodec_oal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_oal.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_utility.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvp8dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvp8enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8enc_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libvp9dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp9dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libEGL_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libGLESv1_CM_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libGLESv2_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/audio.primary.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/camera.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/camera.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/consumerir.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/consumerir.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/gatekeeper.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/gps.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/gralloc.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/hwcomposer.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/lights.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/lights.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/memtrack.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/sensors.mt6795.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/lib3a.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/lib3a_sample.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a_sample.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libIMGegl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libIMGegl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libJpgDecPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libJpgDecPipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libJpgEncPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libJpgEncPipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libMtkH264SecVdecTLCLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMtkH264SecVdecTLCLib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libMtkH264SecVencTLCLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMtkH264SecVencTLCLib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMtkOmxCore.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libPVROCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libPVROCL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libSwJpgCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSwJpgCodec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaed.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaed.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocompensationfilter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocomponentengine.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocustparam.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiodcrflt.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiosetting.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbessound_hd_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libblisrc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libblisrc32.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetooth_mtk_pure.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libbluetoothdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetoothdrv.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libbwc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbwc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.camadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camadapter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.camnode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camnode.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.camshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camshot.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.device1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.device1.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.exif.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.exif.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.exif.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.exif.v3.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.halsensor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.halsensor.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.iopipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.iopipe.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.metadata.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.metadata.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.metadataprovider.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.metadataprovider.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.paramsmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.paramsmgr.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.sdkclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.sdkclient.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.utils.cpuctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.utils.cpuctrl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam1_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam1_utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam3_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_utils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam_hwutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_hwutils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam_mmp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_mmp.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcam_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_platform.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcamalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamalgo.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcamdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamdrv.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcameracustom.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libccci_util.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libccci_util.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcustom_nvram.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcvsd_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libdngop.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdngop.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libfeatureio.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureio.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfile_op.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libfmcust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfmcust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libgas.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgas.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libglslcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libglslcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libgpu_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgpu_aux.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libhwm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwm.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libimageio.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimageio.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libimageio_plat_drv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimageio_plat_drv.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libm4u.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libm4u.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmatv_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmatv_cust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmdfx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdfx.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmemtrack_GL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmemtrack_GL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmhalImageCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmhalImageCodec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmmprofile.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmprofile.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmmsdkservice.feature.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmsdkservice.feature.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmmsdkservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmsdkservice.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmrdump.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmrdump.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmsbc_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtcloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtcloader.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtk_drvb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk_drvb.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtk_mmutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk_mmutils.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtkcamera_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkcamera_client.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtkjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkjpeg.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtklimiter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkshifter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libn3d3a.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libn3d3a.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_daemon_callback.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_platform.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libnvram_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_sec.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvramagentclient.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/liboclcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liboclcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libperfservicenative.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperfservicenative.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libpq_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpq_cust.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libpq_prot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpq_prot.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libpqservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpqservice.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libpvrANDROID_WSEGL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpvrANDROID_WSEGL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspeech_enh_lib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libsrv_init.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsrv_init.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libsrv_um.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsrv_um.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefrighthw.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libufwriter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libufwriter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libusc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libusc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libvcodec_cap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodec_cap.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodec_utility.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwvhidl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libyasalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libyasalgo.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libwvdrmengine.so \
    vendor/xiaomi/hermes/proprietary/vendor/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/ueventd.rc \
    vendor/xiaomi/hermes/proprietary/vendor/usr/keylayout/ACCDET.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/ACCDET.kl \
    vendor/xiaomi/hermes/proprietary/vendor/usr/keylayout/atmel_mxt_ts_T100_touchscreen.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/atmel_mxt_ts_T100_touchscreen.kl \
    vendor/xiaomi/hermes/proprietary/vendor/usr/keylayout/mtk-tpd.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/mtk-tpd.kl

PRODUCT_PACKAGES += \
    libnvram \
    libdpframework.vendor \
    libcam.client \
    libcam_utils \
    libvcodecdrv \
    libion_mtk \
    libcam.utils.sensorlistener \
    libged \
    librilmtk \
    mtk-ril \
    pvrsrvctl \
    mnld \
    libmtk_symbols \
    libaeabi_shim
